### ISSUE TITLE
Whitelisting ?

### ISSUE THREAD

**Issue by ychaouche** [dsoares/roundcube-blacklist#1]
What should be changed in the code to make the plugin work in the other way : block every country except those listed in the whitelist ? (allow every logins)

**Comment by ychaouche** [comment]
Can it be a simple matter of inversing the ifs and turning ANDs into ORs ? What do you think of this pseudo-code  :

```
public function authenticate($args){
    [..]
    if (user in WL) OR (ip in WL) OR (country in WL) {
       return $args
    }
    // else
    if log == true {
        sprintf('login for %s %s %s denied : not in whitelist', $username,$IP,$country)
    }
    $args['abort'] = true;
    return $args;
}
```

**Comment by dsoares** [comment]
It seems to me that your pseudo-code is fine :)

**Comment by ychaouche** [comment]
Thanks for the feedback. I will try to find a way to have the plugin be easily configured as a whitelist or as a blacklist. I am thinking about adding a new configuration $rcube->config["blacklist_mode"] with two values "blacklist" and "whitelist" then write code accordingly.

**Comment by ychaouche** [comment]
@dsoares, requesting some help if possible, here's what I tried but the code below doesn't get the country properly, see userlog excerpt at the end 

```
  private function _get_blacklist_config($rcmail){
    foreach (array('usernames', 'ips', 'countries') as $i) {
      $blacklist[$i] = $rcmail->config->get('whitelist_'.$i, array());
    }
    return $blacklist;
  }

  private function _get_country($ip){
    $geo = geolocation::get_instance()->get_geolocation($ip);
    if (is_string($geo) or $geo == false)
      return "<error>";
    return $geo['country'];
  }

  public function authenticate($args){
    $this->load_config();
    // prepare all the necesary ingredients                                                                                                                                                                                                  
    $rcmail           = rcmail::get_instance();
    $blacklist_config = $this->_get_blacklist_config($rcmail);
    $username         = $args['user'];
    $ip               = $ip = rcube_utils::remote_addr();
    $country          = $this->_get_country($ip);

    // the ip or the country needs to be in the whitelist                                                                                                                                                                                    
    if (in_array($ip,$blacklist_config['ips'])
        or
        in_array($country,$blacklist_config["countries"]))
      return $args;

    // else                                                                                                                                                                                                                                  
    $msg = sprintf("Access denied for %s from %s <%s> : not in the whitelist", $username, $country, $ip);
    rcube::write_log("userlogins",$msg);

    $args['abort'] = true;
    return $args;
  }
}
```

Here's what's logged in userlogins

`02-Apr-2018 15:26:02 +0100]: <7vpkf1rr> Access denied for dzapioudza from  <69.30.218.150> : not in the whitelist`


There should be the country there, right after from, but it's simply not there.

Thanks for any help.

**Comment by ychaouche** [comment]
I added a log line to see what's returned in $geo : 

```
  private function _get_country($ip){
    $geo = geolocation::get_instance()->get_geolocation($ip);
    rcube::write_log("userlogins",json_serialize($geo));
    if (is_string($geo) or $geo == false)
      return "<error>";
    return $geo['country'];
  }
```

It logs 
```
`[02-Apr-2018 15:32:58 +0100]: <7vpkf1rr> {"city":"","region":"","country":""}`
```

**Comment by ychaouche** [comment]
Changing the geolocation plugin source from system to geoiptool resolves the problem

```
[02-Apr-2018 15:48:40 +0100]: <7vpkf1rr> {"city":"Kansas City","region":"Missouri","country":"United States"}
[02-Apr-2018 15:48:40 +0100]: <7vpkf1rr> Access denied for dzaezaa from United States <69.30.218.150> : not in the whitelist
```
I therefor infer that the problem lies with my system's geoip tool (the php module ?)

**Comment by dsoares** [comment]
Yes, the problem is your local system's GeoIP tools.
Read the information about the parameter `geolocation_fetch_method` in `config.inc.php.dist` of the [Geolocation plugin](https://github.com/dsoares/Roundcube-Plugin-Blacklist).

For more information about how to configure your system's GeoIP tools, see the [Geo IP Location](http://php.net/manual/en/book.geoip.php) PHP extension and the [Maxmind](https://dev.maxmind.com/geoip/) information.
