### ISSUE TITLE
Installed plugin

### ISSUE THREAD

**Issue by Blisk** [dsoares/roundcube-blacklist#2]
I install the plugin but it doesn't show up in roundcubemail
anything else to check?

**Comment by dsoares** [comment]
Hi,
Thank you for trying this plugin.
The plugin does not have a graphical interface. It is meant to work when the user tries to authenticate into Roundcube.
To test if it is working, block an username in `plugins/blacklist/config.inc.php` like this:

```php
$config['blacklist_usernames'] = array('your_username_to_block');
```
and try to authenticate with that user. (or similar, trying to block an user IP).
